apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: retail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: 187483722887.dkr.ecr.us-east-1.amazonaws.com/my-app/retail-ui:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: retail
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ui
  type: ClusterIP
