apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: 187483722887.dkr.ecr.us-east-1.amazonaws.com/my-app/retail-orders:latest
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: retail
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: orders
  type: ClusterIP
