name: Terraform Plan (PR)

on:
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsTerraformRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=infra/terraform init -input=false

      - name: Terraform Plan
        run: terraform -chdir=infra/terraform plan -input=false -out=tfplan || true

      - name: Upload tfplan (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/terraform/tfplan
